// client/src/components/Navbar.jsx
import React from 'react';
import {Link} from 'react-router';

export default class App extends React.Component {

  render() {
    return <nav className="navbar navbar-toggleable-md navbar-light bg-faded">
            <button className="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <a className="navbar-brand" href="#">Game Night Buddy</a>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav mr-auto">
                <li className="nav-item">
                  <Link className="nav-link" to="#">Home</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" to="collection">Collection</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" to="members">Members</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" to="matches">Matches</Link>
                </li>
              </ul>
            </div>
          </nav>
  }

}

// src/app/components/navbar/navbar.component.ts
import {Component, OnInit, Input} from '@angular/core';

import {User} from '../../models/user.model';
import {AuthService} from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  @Input() user: User;

  constructor(private authService: AuthService) { }

  ngOnInit() {
  }

  login() {
    this.authService.loginWithFacebook();
  }

  logout() {
    this.authService.logout();
  }

}

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Game Night Buddy</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" routerLink="/" routerLinkActive="active">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/collection" routerLinkActive="active">Collection</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/members" routerLinkActive="active">Members</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/matches" routerLinkActive="active">Matches</a>
      </li>
      <li class="nav-item" *ngIf="user && user.uid">
        <a class="nav-link" (click)="logout()">Logout</a>
      </li>
      <li class="nav-item" *ngIf="!user || !user.uid">
        <a class="nav-link" (click)="login()">Login</a>
      </li>
    </ul>
  </div>
</nav>
